### ISSUE TITLE
Error building on Windows

### ISSUE THREAD

**Issue by kabrepos** [hrbrmstr/hrbrmisc#1]
Hello. Had a problem building the package on Windows using devtools::install_github("hrbrmstr/hrbrmisc"). The error was with regards to object files not recognized. It turns out that the src directory has object files that seem to be tracked by git. I had to download the master and delete the "_.o" files and then issue devtools::install("PATH_TO_UNZIPPED_SOURCE_OF_PACKAGE") from inside R to successfully build the package. It might be helpful to to create a .gitignore file that contained "src/_.o" (without the quotes), so that this issue is resolved for those who want to install from Github directly. Thanks.

**Comment by ghost** [comment]
thx for the note. I've removed all Rcpp dependencies from the pkg now, so try reinstalling it. I'm going to keep Rcpp stuff in a new `hrbrmiscpp` package.

**Comment by kabrepos** [comment]
It installs fine now.
