### ISSUE TITLE
Certain fonts don't work in RMarkdown

### ISSUE THREAD

**Issue by bhaskarvk** [hrbrmstr/hrbrmisc#3]
e.g. `theme_hrbrmstr_an`, I get the following warning

```
In grid.Call(L_textBounds, as.graphicsAnnot(x$label),  ... :
  font family 'ArialNarrow' not found in PostScript font database
```

I tried adding
```r
library(extrafont)
loadfonts()
```

Output format is `markdowntemplates::bulma`

**Comment by hrbrmstr** [comment]
hrm. interesting issue. shld be "fun" debugging O_o

**Comment by bhaskarvk** [comment]
How is 'ArialNarrow' mapped to the actual font installed ?
Could it be because `element_text` expects `family` and `face` in two diff. arguments, while you're passing the font name in the family argument and leaving our the face argument ?

```
extrafont::fonttable() %>% 
  dplyr::filter(FamilyName=='Arial Narrow') %>% 
  dplyr::select(FullName, FamilyName, FontName)

                  FullName   FamilyName               FontName
1             Arial Narrow Arial Narrow            ArialNarrow
2        Arial Narrow Bold Arial Narrow       ArialNarrow-Bold
3 Arial Narrow Bold Italic Arial Narrow ArialNarrow-BoldItalic
4      Arial Narrow Italic Arial Narrow     ArialNarrow-Italic
``` 

```r
hrbrmisc::theme_hrbrmstr_an
function (...) 
{
    theme_hrbrmstr(base_family = "ArialNarrow", plot_title_family = "ArialNarrow-Bold", 
        subtitle_family = "ArialNarrow-Italic", caption_family = "ArialNarrow", 
        ...)
}
```

**Comment by hrbrmstr** [comment]
Aye, try the new `hrbrthemes` pkg ;-) 

the default is Arial Narrow but avoids the `FontName` shortcut in favor of explicit setting of base `family` and `face`. 

I _may_ have this in a local copy of `hrbrmisc` that also has more stuff in it that I'm not sharing ;-)
